# Site settings
title: Блог мрачного программиста
email: bavadim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        Привет! Меня зовут Вадим, я программист и я люблю свою работу. Это блог о моем видении последних и не очень событий, веяний и технологий в мире IT.  
baseurl: "" # the subpath of your site, e.g. /blog/
main_page: "/blog.html"
url: "http://bavadim.me" # the base hostname & protocol for your site
twitter_username: JustVadik
github_username:  bavadim

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

highlighter: pygments
github: git@github.com:bavadim/bavadim.github.io.git
